Repository w3c/wot-profile, pull requests merged in 2022-05, with the labels that each got.

#181 Implementation Report and Assertion Markup Fixes
  index.html
  testing/README.md
  testing/assertions.csv
  testing/atrisk.css
  testing/extractFile.js
  testing/inputs/atrisk.csv
  testing/inputs/categories.csv
  testing/inputs/depends.csv
  testing/inputs/extra-asserts.html
  testing/inputs/impl.csv
  testing/inputs/implementations/.keep
  testing/inputs/interop/template.csv.t
  testing/inputs/json-schema-testable.csv
  testing/inputs/results-template.csv
  testing/inputs/results/.keep
  testing/inputs/templates/interop.html
  testing/inputs/templates/report.html
  testing/inputs/templates/testspec.html
  testing/inputs/testing-atrisk.csv
  testing/inputs/testspec.html
  testing/manual.csv
  testing/output.log
  testing/report.html
  testing/suppressed.csv
  testing/template.csv
Labels: close-next-week

#127 Add timestamps to actions protocol binding - closes #101
  index.html
Labels: ready to merge

#206 Security + privacy section
  index.html
Labels: security, privacy
