Repository w3c/wot-profile, pull requests merged in 2022-03, with the labels that each got.

#180 Cleanup terminology
  index.html
Labels: editorial

#133 Reinstating the Open Issues section
  index.html
Labels: editorial, ready to merge

#118 Remove redundant Accept headers - closes #113
  index.html
Labels: ready to merge

#148 Specify JSON serialisation of Problem Details Format - closes #142
  index.html
Labels: ready to merge

#147 Update references to WoT Architecture 1.1 - closes #144
  index.html
Labels: editorial

#146 Update references to WoT Thing Description 1.1 - closes #143
  index.html
Labels: editorial

#135 Define order of arrays in queryallactions - closes #104
  index.html
Labels: ready to merge
