Repository w3c/wot-profile, pull requests merged in 2022-02, with the labels that each got.

#176 OOTBI section
  index.html
Labels: requirements, ready to merge

#175 incorporating accepted requirements
  index.html
Labels: requirements, ready to merge

#117 Add Identifier section to Core Profile - closes #111
  index.html
Labels: ready to merge

#130 Add Use cases section
  index.html
Labels: use case, ready to merge
